version: '3.4'

services:
  nginx:
    # build: ./nginx
    image: docker.io/soybackend/lumenconcept-product-nginx:v4
    depends_on:
     - django
    ports:
      - "8000:80"
    networks:
      - webnet

  django:
    # build: ./app
    command: /usr/local/bin/gunicorn lumenconcept_product.wsgi:application -w 2 -b :8000
    env_file: .env
    image: docker.io/soybackend/lumenconcept-product-service:v5
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        order: start-first

      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
    networks:
      - webnet
networks:
  webnet:
