# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=36, verbose_name='Code'),
        ),
    ]
